### ISSUE TITLE
Unable to have multiple root in single file

### ISSUE THREAD

**Issue by ram1505** [njh/node-red-contrib-collector#1]
Hi
I'm trying to generate a single xml file with different payloads. However, I'm unable to make multiple roots with the collector node. Please help. Here is what I'm trying to generate in a single file. 

<root1>
  <a>Value A</a>
  <b>Value B</b>
  <c>Value C</c>
</root1>

<root2>
  <a>Value A</a>
  <b>Value B</b>
  <c>Value C</c>
</root2>

**Comment by njh** [comment]
I have never used my collector node in combination with the XML converter.

I suspect that if you want specific XML, you may need to write some JavaScript to do that.

I am also not sure that having multiple roots is valid in XML?

**Comment by ram1505** [comment]
May be I didn't explain myself well. If you look at this page http://www.w3schools.com/xml/xml_display.asp and refer to their cd_catalog.xml example, you can see there will be multiple categories in the xml. If I want to do the same example with your script, how can I achieve similar result? Can you please help?

**Comment by njh** [comment]
You haven't given very much information about what you are trying to achieve, but I suspect that the Collector node is not the best thing to use.

The attached screenshot, sort of works. But it will result in partial documents being sent through.

![screen shot 2016-11-03 at 10 41 02](https://cloud.githubusercontent.com/assets/38734/19962989/4691d930-a1b2-11e6-91e5-72a8262da1ec.png)

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
   <group1>
      <topic1>payload1</topic1>
      <topic2>payload2</topic2>
      <topic3>payload3</topic3>
   </group1>
   <group2>
      <topic4>payload4</topic4>
      <topic5>payload5</topic5>
      <topic6>payload6</topic6>
   </group2>
</root>
```

**Comment by ram1505** [comment]
Thanks. Let me give it a try and will update you. Much appreciated for prompt replies.

**Comment by ram1505** [comment]
Hey, it works perfectly for me. Thanks for the help.

**Comment by ram1505** [comment]
Hi @njh I'm having another issue with this same topic. I was successfully able to categorize topics, however when a particular category has additional parameters, I'm unable to close the topic properly. Please see the example below:
![required_xml](https://cloud.githubusercontent.com/assets/3260482/20343905/42f5a38c-ac2b-11e6-98d4-7bd701db70c9.png)

I really need your help here.

**Comment by njh** [comment]
The XML node help (pane on the right hand side) says:

> You can also pass in a msg.options object to overide all the multitude of parameters.
> See the xml2js docs for more information.

Looking at the READMEs for the XML parser and builder:
- https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/README.md
- https://github.com/oozcitak/xmlbuilder-js

It implies you just have to prefix the JSON key with either '$' or '@', however neither work for me:
<img width="974" alt="screen shot 2016-11-18 at 11 31 49" src="https://cloud.githubusercontent.com/assets/38734/20428763/aff63cbe-ad82-11e6-9ec1-91a3e70f9d7a.png">

The XML node was written by Dave Conway-Jones - it might be worth asking on the Node-RED mailing list:
- https://groups.google.com/forum/#!forum/node-red

**Comment by ram1505** [comment]
I was able to fix with this function node:
`msg.payload = msg.payload.replace(/<\/node [^>]*>/g, "</node>");`
`return msg;`
